### PR TITLE
add Datastore v1 protos

### PR DESCRIPTION
**Pull request by stephenplusplus**

### CODE REVIEW

**Comment by stephenplusplus** [comment]
@callmehiphop does this look right for Bigtable v2?

**Comment by callmehiphop** [comment]
Well, they also updated the admin API and actually split it off into two separate APIs (instance & table).

https://github.com/googleapis/googleapis/tree/master/google/bigtable/admin/v2

**Comment by stephenplusplus** [comment]
Okay, I'll pull that commit out of this PR. Feel free to break our existing API if necessary. Can you send yours soon so we can introduce both Datastore v1 and Bigtable v2 support in 0.6.0?

**Comment by callmehiphop** [comment]
I've been using the function version of `googleProtoFiles()` so if you want to ship without Bigtable, don't feel the need to wait on me :)

Otherwise, yes! I will do it soonish

**Comment by stephenplusplus** [comment]
Cool. gcloud-node talk: It would be better to use the API from `google-proto-files` rather than the function to avoid having a dependency within our Bigtable module, since we already have it in our common module.

**Pull request merged**
